version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: gamezone-container
    environment:
      POSTGRES_DB: 'gamezone'
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5433:5432"
    restart: always